# Numpy review homework

1. Make a numpy matrix from a Python list of lists...

In [3]:
import numpy as np

lol = [[1, 2, 3, 4], [3, 1, 4, 1]]
lolarr = np.array(lol)
print(lolarr)

[[1 2 3 4]
 [3 1 4 1]]


2. Make a 3D numpy matrix from a Python list of lists of lists!

In [4]:
lol3D = [[[1, 2, 3, 4], [3, 1, 4, 1]], [[1, 2, 3, 4], [3, 1, 4, 1]]]
lol3Darr = np.array(lol3D)
print(lol3Darr)

[[[1 2 3 4]
  [3 1 4 1]]

 [[1 2 3 4]
  [3 1 4 1]]]


In [5]:
lol3Darr[0, 1, 2]

4

3. Make a numpy sequence that has the even numbers from 2 up to (and including) 20.

In [9]:
eves = np.arange(2, 21, 2)
print(eves)

[ 2  4  6  8 10 12 14 16 18 20]


4. Create a 5x3 array of Gaussian random numbers. 

In [6]:
grn = np.random.randn(5, 3)
print(grn)

[[-0.537148    0.27059534 -1.04978958]
 [-0.50737581  0.39716231  0.09287207]
 [ 1.59060407  0.73625461  0.85962696]
 [-0.92079572  0.61942878 -1.63923231]
 [ 1.05082532  0.02460737  0.38334018]]


5. Write a script to go through the array created in 3. and announce (print) the value and its row and column indexes.

Hint: Use nested `for` loops - one to loop through the rows and one to loop through the columns.

In [7]:
for i in range(5):
    for j in range(3):
        print(f"The value at {i}, {j} is {grn[i, j]}")

The value at 0, 0 is -0.537147995893178
The value at 0, 1 is 0.27059534357463577
The value at 0, 2 is -1.0497895780309727
The value at 1, 0 is -0.5073758139431729
The value at 1, 1 is 0.3971623123047189
The value at 1, 2 is 0.09287207112917639
The value at 2, 0 is 1.5906040692073813
The value at 2, 1 is 0.7362546111248193
The value at 2, 2 is 0.8596269633730244
The value at 3, 0 is -0.9207957220205448
The value at 3, 1 is 0.6194287812211252
The value at 3, 2 is -1.6392323072832282
The value at 4, 0 is 1.050825319648806
The value at 4, 1 is 0.024607374370306433
The value at 4, 2 is 0.38334018447741497


6. Make an new array out of your random numbers such that the mean is 10 and the standard deviation is 3.

In [10]:
mymean, mysd = 10, 3
new_grn = mysd*grn + mymean
print(new_grn)

[[ 8.38855601 10.81178603  6.85063127]
 [ 8.47787256 11.19148694 10.27861621]
 [14.77181221 12.20876383 12.57888089]
 [ 7.23761283 11.85828634  5.08230308]
 [13.15247596 10.07382212 11.15002055]]


7. Count the number of values in your new array that are below 7.

In [13]:
# short way: 
# sum(sum(new_grn < 7))

# beginner friendly way:
less_than_7 = new_grn < 7
print(f"output of logical test is {less_than_7}")
col_sum = sum(less_than_7)
print(f"sum of the columns are {col_sum}")
total_sum = sum(col_sum)
print(f"total numbers less than 7 is {total_sum}")

ouput of logical test is [[False False  True]
 [False False False]
 [False False False]
 [False False  True]
 [False False False]]
sum of the columns are [0 0 2]
total numbers less than 7 is 2


8. Get the second and third rows of your array created in #4.

In [16]:
myslice = grn[1:3,]
print(myslice)

[[-0.50737581  0.39716231  0.09287207]
 [ 1.59060407  0.73625461  0.85962696]]


9. Compute the overall mean of your array created in #4 and compare it to that from the modified version computed in #6. Does your mean-shifting seem to have worked?

In [17]:
org_mean = np.mean(grn)
new_mean = np.mean(new_grn)
print(org_mean, new_mean)

0.09139837421735415 10.274195122652063


10. Compute the standard deviation of the columns of your array created in #4 and compare them to those from the modified version computed in #6. Does your scaling seem to have worked?

In [18]:
org_std = np.std(grn)
new_std = np.std(new_grn)
print(org_std, new_std)

0.8463165462064172 2.538949638619252
