# Numpy review homework solutions

In [5]:
import numpy as np

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.


1. Make a numpy matrix from a Python list of lists...

In [2]:
a_nested_list = [[2, 4, 4], [3, -1, 8], [-2, 1, 2]]
a_nested_list

[[2, 4, 4], [3, -1, 8], [-2, 1, 2]]

2. Make a 3D numpy matrix from a Python list of lists of lists!

In [26]:
a = [[[1, 2, 3],[4,5,6]],[[7,8,9],[10,11,12]]] # a list of lists of lists!
print(a)

[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]


In [6]:
aa = np.array(a)
print(aa)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


3. Create a 5x3 array of Gaussian random numbers. 

In [7]:
my_rands = np.random.randn(5, 3)
my_rands

array([[-2.19328834,  0.97110121,  0.50205128],
       [ 0.08412925, -0.89284095,  0.59561328],
       [ 0.1518208 ,  0.23454632,  1.03127088],
       [ 0.27117308,  0.4916854 , -1.2629042 ],
       [-2.01671248,  0.83066255,  0.29098483]])

4. Write a script to go through the array created in 3. and announce (print) the value and its row and column indexes.

Hint: Use nested `for` loops - one to loop through the rows and one to loop through the columns.

In [25]:
# go through the cols for each row, use f-string to announce values
for i in range(5) :
    for j in range(3) :
        print(f"the value at {i}, {j} is {my_rands[i,j]}")
        

the value at 0, 0 is -2.1932883391392304
the value at 0, 1 is 0.9711012118919445
the value at 0, 2 is 0.502051277801671
the value at 1, 0 is 0.0841292484111004
the value at 1, 1 is -0.8928409506917592
the value at 1, 2 is 0.5956132794900405
the value at 2, 0 is 0.15182080448195387
the value at 2, 1 is 0.23454632449646046
the value at 2, 2 is 1.0312708812855367
the value at 3, 0 is 0.2711730802856585
the value at 3, 1 is 0.4916854026338551
the value at 3, 2 is -1.2629041960415504
the value at 4, 0 is -2.016712478446415
the value at 4, 1 is 0.8306625511718604
the value at 4, 2 is 0.29098483243230583


5. Make an new array out of your random numbers such that the mean is 10 and the standard deviation is 3.

In [24]:
my_new = my_rands*3 + 10  # scale by the sd and then add on the mean
my_new

array([[ 3.42013498, 12.91330364, 11.50615383],
       [10.25238775,  7.32147715, 11.78683984],
       [10.45546241, 10.70363897, 13.09381264],
       [10.81351924, 11.47505621,  6.21128741],
       [ 3.94986256, 12.49198765, 10.8729545 ]])

6. Count the number of values in your new array that are below 7.

In [12]:
print(sum(sum(my_new < 7))) # logical indexing + sum down the cols + sum

3


7. Make a numpy sequence that has the even numbers from 2 up to (and including) 20.

In [15]:
my_seq = np.arange(2, 21, 2)  # start (incl), stop (excl), step
my_seq

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

8. Get the second and third rows of your array created in #5.

In [19]:
print(my_new[1:3,:])

[[10.25238775  7.32147715 11.78683984]
 [10.45546241 10.70363897 13.09381264]]


9. Compute the mean of the columns of your array created in #5.

In [23]:
my_new.mean(axis=0) # mean down the rows

array([ 7.77827339, 10.98109272, 10.69420964])