# Numpy Review

In this review, we are going to refresh our memories about the Numpy package. Numpy (numerical Python) is the basic engine that turns Python into a tool for data analysis. Anything "data sciency" that you do in Python will rely on Numpy at some point, either explicitly (when calling Numpy fuctions directly), or implicitly (when, e.g., using Pandas).

The point of Numpy is do make working with data in Python easier and faster. Here, we going to remind ourselves of basic Numpy functionality.

## Python lists

First, let's look at a basic Python list:

In [32]:
a_list = [2, 4, 6, 8]

---

Just to warm up, let's get some items from our list via *indexing*:

Get the first number from the list (the "zeroith" number in Pythonese):

Get the last two numbers:

---

Now let's make a *nested* Python list:

In [43]:
a_nested_list = [[2, 4], [3, -1], [-2, 1]]

Remember that a Python list can hold data of different types, lengths, etc., but this list is special; it is a *list of lists* all of the same length.

Let's have a look:

In [39]:
print(a_nested_list)

[[2, 4], [3, -1], [-2, 1]]


How would we get the first entry in the second list? 

We could do it in two steps... first, get the second list:

In [40]:
sec_list = a_nested_list[1]

And then get the first entry:

In [41]:
my_num = sec_list[0]
print(my_num)

3


Conveniently, we can just do this in one go:

In [42]:
my_num = a_nested_list[1][0]
print(my_num)

3


This does the same thing without having to invoke the intermediate variable `sec_list`. 

While this list-of-lists construct might seem a little abstract, there is actually a nice what to wrap our heads around it, which is to think of it as a *matrix*.

> Unfortunately, no one can be told what the Matrix is. You have to see it for yourself. *- Morpheus*

Here is an example of a matrix:

![A matrix](./images/mailboxes.png)

A ***matrix*** is a 2 dimensional (2D) arrangement of things and, for our purposes, the things are data of one form or another (numbers, strings, timestamps, etc.).

These mailboxes are numbered sequentially, because there are other mailboxes in other matrices and that's just how the USPS rolls. But, notice that, for *this* matrix of mailboxes, there is another way in which we could uniquely refer to each mailbox. Specifically, we could uniquely specify each mailbox by the *row* it is in and the *column* it is in.

For example, the open mailbox with the key in the door is in the 2nd row and the 4th column or, in terms of Python indexes, the mailbox is at location [1, 3]. 

So, we can think of matrix as an arrangement of data that has a built in ***spatial coordinate system*** used to refer to the items of data.

Here's another Python list of lists:

In [46]:
another_nested_list = [[3.3, 2.3, 2.2], [1.2, 7.8, 8.7], [4.8, 2.2, 6.5],
                       [1.5, 7.5, 9.5], [5.9, 1.6, 7.7]]

As far as Python is concerned, this is just a list that happens to contain 5 lists, each of length 3:

In [48]:
print(f'Another nested Python list: {another_nested_list}')

Another nested Python list: [[3.3, 2.3, 2.2], [1.2, 7.8, 8.7], [4.8, 2.2, 6.5], [1.5, 7.5, 9.5], [5.9, 1.6, 7.7]]


But it makes sense for our human brains to think about it as a 2D arrangement of data, like this: 

| row # | Col # | | | | |
| ---- | ---- | ---- | ---- | ---- | ---- |
|   | 0 | 1 | 2 | 3 |  4 | 5 |
| 0 | 3.3 | 1.2 | 4.8 | 1.5 |  5.9 | 9.0 |
| 1 | 2.3 | 7.8 | 2.2 | 7.5 |  1.6 | 8.1 |
| 2 | 2.2 | 8.7 | 6.5 | 9.5 |  7.7 | 5.2 |

Now we can think of the Python indexes used to access the data as spatial ***row*** and ***column*** coordinates. For example:

In [49]:
another_nested_list[2][1]

2.2

fetches the data value in the second row (row index 1) and the third column (column index 2). 

Even though, in Python terms, `another_nested_list` is just a list of lists that all happen to be of the same length, it's very helpful for us to map data like this onto a matrix and think of the indexes as coordinates.

## Numpy

Numpy is a big and powerful package, but you can think of it's most basic function as making this matrix-like way of thinking about data explicit, as opposed to just a cute way of thinking about lists of lists.

To use numpy, we first import it. Traditionally, it is imported under the name "`np`".

In [2]:
import numpy as np

Now we can convert our latest nested list into a numpy matrix using numpy's `array()` function:

In [51]:
our_numpy_matrix = np.array(another_nested_list)

Let's look at our new matrix!

In [55]:
print(our_numpy_matrix)

[[3.3 2.3 2.2]
 [1.2 7.8 8.7]
 [4.8 2.2 6.5]
 [1.5 7.5 9.5]
 [5.9 1.6 7.7]]


And compare it to the Python list from which we created it.

In [62]:
print(another_nested_list)

[[3.3, 2.3, 2.2], [1.2, 7.8, 8.7], [4.8, 2.2, 6.5], [1.5, 7.5, 9.5], [5.9, 1.6, 7.7]]


We can see that the numpy version has made the spatial row x column arrangement explicit.

Now, getting data values is easy peasy, we just index into our new matrix with row and column coordinates of a desired value:

In [63]:
our_numpy_matrix[2,0] # get the data at the third row and first column

4.8

Let's see what data type our new matrix is, according to Python:

In [64]:
type(our_numpy_matrix)

numpy.ndarray

So our new matrix is a Python object made by numpy of type "ndarray", which is short for "N-dimesional array" – we'll unpack this in a bit.

But our object contains other objects (in that Pythonic way), so let's see what they are:

In [65]:
type(our_numpy_matrix[2,0])

numpy.float64

So they are floating point numbers, also defined in numpy, that presumably have a few more bells and whistles that regular Python floats (the 64 at the end means that 64 bits are used to store each number; this is the number's *precision*.

You may have noticed that our new matrix is a little different than the way we laid out our numbers in the table above. There, we made each sub-list into a column, whereas the `array` function seems to have made each list into a row.

Fear not! Numpy objects, like all Python objects "know" how to do things; they have *methods*. The need to turn the rows into columns and vice versa is very common – it is called *transposing* a matrix – so numpy arrays have a *transpose* method `T`.

In [61]:
transposed_matrix = our_numpy_matrix.T
print(transposed_matrix)

[[3.3 1.2 4.8 1.5 5.9]
 [2.3 7.8 2.2 7.5 1.6]
 [2.2 8.7 6.5 9.5 7.7]]


Notice that the value 4.8 used to be in the third row of the first column, but now it's coordinates have been flipped:

In [66]:
transposed_matrix[0,2] # new location of 4.8

4.8

In [67]:
transposed_matrix[2,0] # value at the old location

2.2

---

In the code cell below, make a Python list of lists, create a numpy matrix from it, transpose it, and access 3 of it's values.

### Numpy arrays 

So far, we've been talking about our data above as a "matrix", yet we used the `array()` function to make it, and Python tells us that our matrix is an `ndarray` – what's going on?

#### Types of arrays

"Array" is a general term for a structured collection of data, and can have any number of dimensions (hence "ndarray" for "N-dimensional array"). Here's an (empty) 3 dimensional array:

![A 3D array](images/array.png)

If this array were named "phred", we would index it just like above, but with an extra index – the coordinate specifying the location along the third dimension. So `phred[5, 5, 3]` would specify the bottom right location just peeking out on the fourth – what? – "page" of the array.

Though arrays can have any number of dimensions, lower-dimensional arrays are common and get their own special names.

A "matrix" is an array of 2 dimensions. As you already know, a matrix is a universal format for data and is preferably in "tidy" format, where each row is an observation and each column is a variable.

A "vector" is a list of numbers, so named because a simple list of numbers is used in math (linear algebra) and physics to specify vectors (such as force). Vectors can be 

* "row vectors" - a matrix with a single row
* "column vectors" - a matrix with a single column
* a list of numbers with only a single dimension, like a Python list

Finally, in this lingo, a single number is referred to as a "scaler" (because multiplying a vector by a number scales the length of the vector without changing its direction).

---

In the cell below, make a Python list or tuple containing the x and y coordinates of a point (any point you like – I'm a big fan of x=3, y=1 personally). On a piece of paper or a drawing program or whatever, plot the point in an x,y coordinate system, and draw an arrow – a vector! – from the origin to your point.

In [55]:
v = (3, 1)

Now convert your Python object into a numpy array.

In [56]:
va = np.array(v)

Get the shape of your new vector using the `shape` method (used just like the `T` method above).

In [57]:
va.shape

(2,)

Multiply your vector by 2 (if your vector is named "Velma", then you would literally do `Velma * 2`).

Plot your new vector and confirm that the multiplication *scaled* the original vector up by a factor of 2 without changing its direction!

---

We've just illustrated an awesome thing about numpy ndarrays: if we want to do simple operations on an entire array, we don't need to do it element-by-element, we just do it on the entire array in one go! Despite operating on arrays in general, this property is referred to as "*vectorization*" of operations.

#### Making numpy arrays 

##### arrays from lists or tuples

We've already seen that we can make numpy arrays from Python lists. Like this:

In [17]:
print(f'A python list: {a_list}')

a_numpy_thing = np.array((a_list))

print(f'A numpy thing: {a_numpy_thing}')

A python list: [2, 4, 6, 8]
A numpy thing: [2 4 6 8]


Or this:

In [12]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

---

In the cell below, confirm that you can make a numpy array from a Python tuple.

##### ones and zeros

If we're creating or reading in data from a source other than a Python list or tuple, we need a place to put it. To make new arrays to hold stuff, we first create an array filled with something. Most of the time, it doesn't matter what we fill it with. We commonly fill new arrays with ones or zeros.

In [22]:
a_vec = np.ones((3,2))
print(f'an array of ones:\n {a_vec}')

an array of ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


---

In the cell below, make an array of zeros.

---

##### Any number 

We can also initialize an array to any value we want.

In [26]:
the_answer = np.full((3,3), 42)
print(f'Every cell has the answer!:\n {the_answer}')

Every cell has the answer!:
 [[42 42 42]
 [42 42 42]
 [42 42 42]]


---

In the cell below, get the same result as above (a 3x3 array of 42s) using 1) `np.ones` and 2) `np.zeros`. 
(Hint: take advantage of vectorization using `*` and `+`)

##### random numbers

In data science, we often add random noise to simulations in order to capture the random variability present in the universe and the data we get from it. We can do this using any number of functions in `np.random`. For example

In [41]:
my_noise = np.random.randn(4,4)
print(f'C\'mon feel the noise! \n {my_noise}')

C'mon feel the noise! 
 [[-0.24068232 -1.08455527 -0.4804745  -0.1219516 ]
 [-0.17305515  1.30790772  0.06905236  0.25602269]
 [ 0.79909262 -0.736747    0.88863157  0.34500431]
 [-0.66731001  0.18111199 -0.43213863 -0.01166869]]


Which made normally distributed (Gaussian) noise. 

We can also make noise that is uniformly distributed:

In [42]:
unif_noise = np.random.rand(4,4)
print(f'Moar noise! \n {unif_noise}')

Moar noise! 
 [[0.08955967 0.09887821 0.65576599 0.86472394]
 [0.7854378  0.68453904 0.56016456 0.38530534]
 [0.67379837 0.89458098 0.49068116 0.21693567]
 [0.9499564  0.42646964 0.36448562 0.21986473]]


Or we can make random integers:

In [43]:
int_noise = np.random.randint(1, 11, (4,4))
print(f'Random integers! \n {int_noise}')

Random integers! 
 [[ 3 10  7  9]
 [ 7 10  6  2]
 [ 5  4  3  4]
 [ 7 10  8  4]]


##### the identity matrix

Finally, we can make an "identity matrix", a matrix with 1s running down the diagonal. It's useful for linear algebra applications, and is included there only for completeness.

In [33]:
aye = np.eye(4,4)
print(f'Aye aye Cap\'n! \n {aye}')

Aye aye Cap'n! 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


---

In the cell below, make a 6x6 array containing random integers from -10 to 10.

#### "vectorized" operations 

As mentioned above, most of the common Python operators become *vectorized* in numpy, which means that we can to the same thing to every element of our arrays in one go.

let's add 10 to all our Gaussian random numbers from above.

In [44]:
amp_noise = my_noise + 11
amp_noise

array([[10.75931768,  9.91544473, 10.5195255 , 10.8780484 ],
       [10.82694485, 12.30790772, 11.06905236, 11.25602269],
       [11.79909262, 10.263253  , 11.88863157, 11.34500431],
       [10.33268999, 11.18111199, 10.56786137, 10.98833131]])

Let's see which ones go to 11!

In [46]:
amp_noise >= 11

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True, False,  True,  True],
       [False,  True, False, False]])

If arrays are the same size, we can do element-by-element things easily.

Which elements of the Gaussian noise are greater than the corresponding elements of the uniform noise?

In [54]:
my_noise > unif_noise

array([[False, False, False, False],
       [False,  True, False, False],
       [ True, False,  True,  True],
       [False, False, False, False]])

Add our Gaussian and integer noise element-by-element:

In [50]:
my_noise + int_noise

array([[ 2.75931768,  8.91544473,  6.5195255 ,  8.8780484 ],
       [ 6.82694485, 11.30790772,  6.06905236,  2.25602269],
       [ 5.79909262,  3.263253  ,  3.88863157,  4.34500431],
       [ 6.33268999, 10.18111199,  7.56786137,  3.98833131]])

Divide our identity matrix by our integer noise – everything off the main diagonal should be zero...

In [49]:
aye / int_noise

array([[0.33333333, 0.        , 0.        , 0.        ],
       [0.        , 0.1       , 0.        , 0.        ],
       [0.        , 0.        , 0.33333333, 0.        ],
       [0.        , 0.        , 0.        , 0.25      ]])

---

In the cell below, make a 10x5 matrix containing normally distributed random numbers with a mean of about 100 and a standard deviation of about 15 using vectorized operations.

#### Making numpy sequences 

When computing things like functions (in the math sense), we need to start by laying down an x-axis (a working domain of the function). 

#### Indexing cells 

Cells and subsets of numpy arrays are accessed – "indexed" – much like Python lists and tuples are.

Here are some examples of array indexing from Python for Data Analysis by Wes McKinney:

![Array Indexing](images/arrayIndexing.png)

#### Indexing rows and columns

#### Indexing subsets ("slicing")