# Numpy review homework

1. Make a numpy matrix from a Python list of lists...

In [3]:
import numpy as np

lol = [[1, 2, 3, 4], [3, 1, 4, 1]]
lolarr = np.array(lol)
print(lolarr)

[[1 2 3 4]
 [3 1 4 1]]


2. Make a 3D numpy matrix from a Python list of lists of lists!

In [4]:
lol3D = [[[1, 2, 3, 4], [3, 1, 4, 1]], [[1, 2, 3, 4], [3, 1, 4, 1]]]
lol3Darr = np.array(lol3D)
print(lol3Darr)

[[[1 2 3 4]
  [3 1 4 1]]

 [[1 2 3 4]
  [3 1 4 1]]]


In [5]:
lol3Darr[0, 1, 2]

4

3. Make a numpy sequence that has the even numbers from 2 up to (and including) 20.

4. Create a 5x3 array of Gaussian random numbers. 

In [6]:
grn = np.random.randn(5, 3)
print(grn)

[[-0.537148    0.27059534 -1.04978958]
 [-0.50737581  0.39716231  0.09287207]
 [ 1.59060407  0.73625461  0.85962696]
 [-0.92079572  0.61942878 -1.63923231]
 [ 1.05082532  0.02460737  0.38334018]]


5. Write a script to go through the array created in 3. and announce (print) the value and its row and column indexes.

Hint: Use nested `for` loops - one to loop through the rows and one to loop through the columns.

In [7]:
for i in range(5):
    for j in range(3):
        print(f"The value at {i}, {j} is {grn[i, j]}")

The value at 0, 0 is -0.537147995893178
The value at 0, 1 is 0.27059534357463577
The value at 0, 2 is -1.0497895780309727
The value at 1, 0 is -0.5073758139431729
The value at 1, 1 is 0.3971623123047189
The value at 1, 2 is 0.09287207112917639
The value at 2, 0 is 1.5906040692073813
The value at 2, 1 is 0.7362546111248193
The value at 2, 2 is 0.8596269633730244
The value at 3, 0 is -0.9207957220205448
The value at 3, 1 is 0.6194287812211252
The value at 3, 2 is -1.6392323072832282
The value at 4, 0 is 1.050825319648806
The value at 4, 1 is 0.024607374370306433
The value at 4, 2 is 0.38334018447741497


6. Make an new array out of your random numbers such that the mean is 10 and the standard deviation is 3.

7. Count the number of values in your new array that are below 7.

8. Get the second and third rows of your array created in #5.

9. Compute the mean of the columns of your array created in #5.